#!/usr/bin/env python
#
# Generated by Clude 4.8 with Nico Zucca
#
# Compute a stable map -> world static transform from N manually captured robot positions.
#
# The yaw of the map->world transform is recovered from POSITION only (no orientation
# reading), by least-squares fitting a 2D rigid transform over all captured point pairs.
# Position is far steadier than a single-shot orientation estimate, so the alignment is
# much more reliable.
#
# The path between captures is irrelevant -- only the captured positions matter -- and the
# relative angle between positions does not matter either. Just spread the captures out;
# a larger spread improves the angle estimate. Two points is the minimum; more is better.
#
# Assumptions:
#   * map and world are both gravity-aligned (z up), so only yaw differs between them.
#   * base_link and Robot/base_link track the same physical point on the robot.
#     (If they don't, a non-zero RMS residual will warn you.)

import math
import numpy as np
import rospy, tf
from itertools import combinations

# Make input() behave the same on Python 2 (ROS Melodic) and Python 3 (ROS Noetic).
try:
    input = raw_input
except NameError:
    pass

rospy.init_node('compute_bridge_points')
li = tf.TransformListener()
rospy.sleep(1.0)


def capture():
    """Return (base position in map, base position in world) as numpy 3-vectors."""
    li.waitForTransform('map',   'base_link',       rospy.Time(0), rospy.Duration(5))
    li.waitForTransform('world', 'Robot/base_link', rospy.Time(0), rospy.Duration(5))
    (tm, _) = li.lookupTransform('map',   'base_link',       rospy.Time(0))
    (tw, _) = li.lookupTransform('world', 'Robot/base_link', rospy.Time(0))
    return np.array(tm), np.array(tw)


def max_span(P):
    """Largest pairwise distance among a set of 2D points."""
    if len(P) < 2:
        return 0.0
    return max(np.linalg.norm(P[i] - P[j]) for i, j in combinations(range(len(P)), 2))


pts_map, pts_world = [], []
print("Drive the robot anywhere; press ENTER at each spot to capture a point.")
print("Type 'd' then ENTER when done (need at least 2 points).\n")

while True:
    cmd = input("ENTER to capture point %d, or 'd' to finish: " % (len(pts_map) + 1))
    if cmd.strip().lower() == 'd':
        if len(pts_map) >= 2:
            break
        print("  need at least 2 points.")
        continue
    m, w = capture()
    pts_map.append(m)
    pts_world.append(w)
    print("  captured  map=(%.3f, %.3f)  world=(%.3f, %.3f)" % (m[0], m[1], w[0], w[1]))

M = np.array(pts_map)
W = np.array(pts_world)
Mxy, Wxy = M[:, :2], W[:, :2]

span_m, span_w = max_span(Mxy), max_span(Wxy)
if span_m < 0.20:
    print("\nWARNING: points span only %.3f m. Spread them out for a reliable angle." % span_m)
if span_w > 1e-6 and abs(span_m - span_w) / span_w > 0.10:
    print("\nWARNING: map span %.3f m vs world span %.3f m differ >10%%. "
          "Check your frames / lever arm." % (span_m, span_w))

# Least-squares 2D rigid fit (Kabsch): find R, t with  point_map = R * point_world + t.
cM, cW = Mxy.mean(axis=0), Wxy.mean(axis=0)
Mc, Wc = Mxy - cM, Wxy - cW
H = Wc.T.dot(Mc)                                   # 2x2 cross-covariance (world -> map)
U, _, Vt = np.linalg.svd(H)
d = np.sign(np.linalg.det(Vt.T.dot(U.T)))          # guard against a reflection
R2 = Vt.T.dot(np.diag([1.0, d])).dot(U.T)
t_xy = cM - R2.dot(cW)
t_z = float((M[:, 2] - W[:, 2]).mean())            # pure yaw leaves z unchanged

yaw = math.atan2(R2[1, 0], R2[0, 0])
qz, qw = math.sin(yaw / 2.0), math.cos(yaw / 2.0)

# Fit quality: RMS of the per-point residual in the map frame.
pred = Wxy.dot(R2.T) + t_xy
rms = math.sqrt(np.mean(np.sum((Mxy - pred) ** 2, axis=1)))

print("\n%d points | yaw = %.4f rad (%.2f deg) | span = %.3f m | RMS residual = %.4f m"
      % (len(pts_map), yaw, math.degrees(yaw), span_m, rms))
print("rosrun tf2_ros static_transform_publisher %.6f %.6f %.6f %.6f %.6f %.6f %.6f map world"
      % (t_xy[0], t_xy[1], t_z, 0.0, 0.0, qz, qw))
